version: "2"

services:
 server:
  image: klakegg/hugo:0.101.0-ext-ubuntu
  command: server -D -b nyavarlden.se
  networks:
    - main
  volumes:
    - "./nya_varlden:/src"
  ports:
    - "80:1313" 
      
networks:
  main: